import = ["/home/gasta/.config/alacritty/dracula.toml"]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
opacity = 0.8

[mouse]
bindings = [
{mouse = "Right", action = "Paste"},
]

[selection]
save_to_clipboard = true
